[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = espidf
monitor_speed = 115200
upload_protocol = esptool
monitor_filters = esp32_exception_decoder, time, colorize
board_build.flash_size = 4MB
; board_build.partitions = partitions.csv