version: "3.8"

services:
  api:
    build: .
    
    container_name: syncflorapot_api
    
    restart: unless-stopped
    
    ports:
      - "3000:3000"
    
    env_file: .env
    
    environment:
      PORT: 3000
      POSTGRES_USER: syncflorapot
      POSTGRES_DB: syncflorapot
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MQTT_URL: mqtt://mqtt:1883

    depends_on:
      db:
       condition: service_healthy
      mqtt:
       condition: service_started
    
    networks:
      - syncflorapot_network

  db:
    image: timescale/timescaledb:latest-pg17
    
    container_name: syncflorapot_db
    
    restart: unless-stopped
    
    env_file: .env
    
    environment:
      POSTGRES_USER: syncflorapot
      POSTGRES_DB: syncflorapot
    
    ports:
      - "5432:5432"
    
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - timescale_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U syncflorapot -d syncflorapot"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    networks:
      - syncflorapot_network

  mqtt:
    image: eclipse-mosquitto:2
    
    container_name: syncflorapot_mqtt
    
    restart: unless-stopped
    
    ports:
      - "1883:1883"
    
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    
    networks:
      - syncflorapot_network

volumes:
  timescale_data:
  mosquitto_data:
  mosquitto_log:

networks:
  syncflorapot_network:
    driver: bridge
