idf_component_register(
    SRCS
        "main.c"
        "core/sensor_state.c"
        "services/srv_display.c"
        "services/srv_hydration.c"
        "services/srv_internet.c"
        "services/srv_monitoring.c"
        "network/wifi_manager.c"
        "drivers/adc_manager/adc_manager.c"
        "drivers/i2c_manager/i2c_manager.c"
        "drivers/display/display.c"
        # "drivers/dht11/dht11.c"
        "drivers/ldr/ldr.c"
        "drivers/moisture/moisture.c"
        "drivers/pump/pump.c"
        "drivers/ultrasonic/ultrasonic.c"
        "dianui/core/dianui_engine.c"
        "dianui/core/dianui_renderer.c"
        "dianui/core/dianui_log.c"
        "dianui/elements/dianui_element.c"
        "dianui/elements/dianui_icon.c"
        "dianui/elements/dianui_qrcode.c"
        "dianui/elements/dianui_shape.c"
        "dianui/elements/dianui_text.c"
        "dianui/animation/dianui_animation.c"
        "dianui/animation/dianui_easing.c"
        "dianui/pages/dianui_pages.c"
        "../lib/qrcode/qrcode_generator.c"
    INCLUDE_DIRS
        "."
        "core"
        "services"
        "network"
        "drivers"
        "drivers/adc_manager"
        # "drivers/dht11"
        "drivers/display"
        "drivers/ldr"
        "drivers/moisture"
        "drivers/pump"
        "drivers/ultrasonic"
        "dianui"
        "dianui/core"
        "dianui/elements"
        "dianui/animation"
        "../lib/qrcode"
)